### ISSUE TITLE
Opening iex shifts part of the editor frame out of the window.

### ISSUE THREAD

**Issue by nyc** [indiejames/atom-iex#28]
![screen shot 2015-07-30 at 12 56 14 am](https://cloud.githubusercontent.com/assets/1140436/8978327/0412e02c-3656-11e5-9d2d-5e8eb0eddc28.png)

I've confirmed this happens on One Light and Atom Light default UI themes. The elements do get shifted back after switching tabs; however, once you've inputted enough lines into iex and have run off the bottom of the screen, the iex tab thinks the buffer is larger than the size of the window, so you can no longer see or scroll to the cursor.

Before switching tabs to reset window:

![screen shot 2015-07-30 at 1 00 44 am](https://cloud.githubusercontent.com/assets/1140436/8978379/82ca24ac-3656-11e5-9d06-b9209a6031e6.png)

After switching tabs:

![screen shot 2015-07-30 at 12 59 35 am](https://cloud.githubusercontent.com/assets/1140436/8978355/4ef2203a-3656-11e5-9460-bf0eb8f92cc7.png)

Note the cursor is no longer visible and you cannot scroll down to it.

**Comment by joshuata** [comment]
A similar problem happens when opening a down split. The split is opened underneath the bottom bar, meaning that when you fill up the repl buffer, the final line is hidden. The issue can be resolved by resizing the split upward by the single line. 

The issue appears to be that repl size is determined without taking into account any top or bottom bars.

I am not familiar with Atom (or CoffeeScript/CSS for that matter), but it looks like the problem may be in `atom-iex/lib/TermView.coffee:199'.

``` coffee
getDimensions: ->
    fakeCol = $("<span id='colSize'>m</span>").css visibility: 'hidden'
    if @term
      @find('.terminal').append fakeCol
      fakeCol = @find(".terminal span#colSize")
      cols = Math.floor (@width() / fakeCol.width()) or 9
      #cols = Math.floor (@width() / 10)  or 9
      rows = (Math.floor (@height() / fakeCol.height()) - 2) or 16
      #rows = Math.floor (@height() / 14)  or 16
      fakeCol.remove()
    else
      cols = Math.floor @width() / 7
      rows = Math.floor @height() / 14

    {cols, rows}
```

**Comment by indiejames** [comment]
I have been able to duplicate this. I will try to get a fix done this weekend.
