### ISSUE TITLE
Twitches after a dash in prompt

### ISSUE THREAD

**Issue by aaronjensen** [indiejames/atom-iex#34]
On atom 1.1.0:

![twitch](https://cloud.githubusercontent.com/assets/8588/10848557/c1c9ea22-7ed9-11e5-8178-fa2c548409a0.gif)

**Comment by indiejames** [comment]
Is this on a Linux platform? I was not able to duplicate this until just now by setting up an ubuntu VM. Frankly I had no idea this package worked at all on Linux (I have only tested on OS X). In any case, until I can fix it on Linux you can disable the cursor blink in the package's prefs and restart your REPL and it should go away (it did for me).

I will also try to test more on Linux now and set up some alternative key bindings using ctrl instead of cmd.

**Comment by aaronjensen** [comment]
Nah, it's on osx. Thanks for the tip on the cursor blink, I can give that a shot.

**Comment by indiejames** [comment]
Just tried this on a different mac and now I see it happening. I'll try to get this fixed.

**Comment by davidmoshal** [comment]
Exactly the same problem with me - on OSX also.
Clearly makes the plugin unusable.

**Comment by indiejames** [comment]
I'm still trying to track this down. Again, try turning off cursor blink for now.

**Comment by indiejames** [comment]
Please try updating to 0.9.21 and let me know if this fixes the issue for you.

**Comment by aaronjensen** [comment]
@indiejames it did not fix the issue.

**Comment by indiejames** [comment]
Hmm. As a sanity check can you verify that you have the 0.9.21 version? If so, can you try uninstalling it then re-installing it?

Thanks

**Comment by aaronjensen** [comment]
verified version, reinstalled, verified problem still exists, sorry :/

**Comment by indiejames** [comment]
Just noticed that this happens for me at certain font sizes and not other.

**Comment by aaronjensen** [comment]
Confirmed fixed, thanks!
